version: "3.8"

services:
  php:
    build: ./docker/php/
    container_name: tp_docker_php_php_container
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: postgres:9.6.24-alpine3.15
    container_name: tp_docker_php_db_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    container_name: tp_docker_php_adminer_container
    ports:
      - 8080:8080
    depends_on:
      - db
